# Generated by Django 5.2.17 on 2026-09-08 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CONFIRM_VEHICLE', 'Confirmed / Published Vehicle'), ('REJECT_VEHICLE', 'Rejected Vehicle Submission'), ('HIDE_VEHICLE', 'Temporarily Hid Vehicle'), ('UNHIDE_VEHICLE', 'Unhid / Restored Vehicle'), ('DELETE_VEHICLE', 'Deleted Vehicle'), ('PROMOTE_USER', 'Granted ROOT / Admin Privileges'), ('DEMOTE_USER', 'Demoted to Regular Member'), ('BAN_USER', 'Banned / Deactivated User'), ('UNBAN_USER', 'Unbanned / Activated User'), ('DELETE_USER', 'Deleted User Account')], db_index=True, max_length=64)),
                ('target_type', models.CharField(db_index=True, max_length=32)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_title', models.CharField(blank=True, max_length=255)),
                ('details', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
