# Generated by Django 5.2.17 on 2026-09-07 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=64)),
                ('model', models.CharField(db_index=True, max_length=64)),
                ('trim', models.CharField(blank=True, max_length=128)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('model_3d', models.CharField(help_text='Path under static/ (e.g. models/bmw_m4_convertible_g83_2021.glb)', max_length=255)),
                ('lat', models.FloatField(help_text='Latitude coordinate for map pin')),
                ('lng', models.FloatField(help_text='Longitude coordinate for map pin')),
                ('location_name', models.CharField(help_text='Street or district in Tbilisi', max_length=128)),
                ('city', models.CharField(db_index=True, default='Tbilisi', max_length=64)),
                ('year', models.PositiveIntegerField(default=2024)),
                ('seats', models.PositiveIntegerField(default=4)),
                ('distance', models.CharField(default='100m', max_length=32)),
                ('walk_time', models.CharField(default='3 min', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserRecentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, null=True)),
                ('viewed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recent_views', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_view_records', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Recent Vehicle View',
                'verbose_name_plural': 'Recent Vehicle Views',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_records', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'User Favourite',
                'verbose_name_plural': 'User Favourites',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'vehicle')},
            },
        ),
    ]
