# Generated by Django 5.2.17 on 2026-09-07 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['-id'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
        migrations.AddField(
            model_name='vehicle',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=90.0, help_text='Daily rental price in GEL (₾)', max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_capacity',
            field=models.PositiveIntegerField(default=60, help_text='Fuel tank capacity in Liters (L)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='vehicles/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image_url',
            field=models.CharField(blank=True, default='images/bmw_m4.png', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner_phone',
            field=models.CharField(blank=True, help_text='Contact phone number auto-filled from owner profile', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'ავტომატიკა (Automatic)'), ('Manual', 'მექანიკა (Manual)'), ('Tiptronic', 'ტიპტრონიკი (Tiptronic)')], default='Automatic', max_length=32),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lat',
            field=models.FloatField(default=41.7151, help_text='Latitude coordinate for map pin'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='lng',
            field=models.FloatField(default=44.8271, help_text='Longitude coordinate for map pin'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='location_name',
            field=models.CharField(default='Rustaveli Ave, Tbilisi', max_length=128),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model_3d',
            field=models.CharField(blank=True, help_text='Path under static/ (e.g. models/bmw_m4_convertible_g83_2021.glb)', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=8),
        ),
        migrations.CreateModel(
            name='RentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(help_text='City where the car is rented', max_length=64)),
                ('rental_days', models.PositiveIntegerField(default=1, help_text='Rental duration in days')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total calculated price', max_digits=10)),
                ('status', models.CharField(default='Confirmed', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vehicles.vehicle')),
            ],
            options={
                'verbose_name': 'Rental Booking',
                'verbose_name_plural': 'Rental Bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
