# Generated by Django 5.2.17 on 2026-09-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_vehicle_options_vehicle_daily_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='model_3d_file',
            field=models.FileField(blank=True, help_text='Uploaded .glb 3D car model', null=True, upload_to='models/'),
        ),
    ]
