# Generated by Django 5.2.17 on 2026-09-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_vehicle_model_3d_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual'), ('Tiptronic', 'Tiptronic')], default='Automatic', max_length=32),
        ),
    ]
