# Generated by Django 5.2.17 on 2026-09-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_rejection_reason_vehicle_reviewed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='views_count',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Total number of times vehicle was opened/viewed'),
        ),
    ]
